defaults:
  - encoder: spacebag_and_vstride_encoder
  - decoder: vstride_decoder
  - processor: space_time_split
  - norm_layer: rmsgroupnorm
_target_: walrus.models.IsotropicModel
hidden_dim: 64
projection_dim: 48
intermediate_dim: 32
processor_blocks: 2
drop_path: 0.0
groups: 4
max_d: 3
causal_in_time: False
include_d: [2, 3]
override_dimensionality: 3
jitter_patches: True
gradient_checkpointing_freq: 0
input_field_drop: 0.0
processor:
  space_mixing:
    _partial_: true
    _target_: walrus.models.spatial_blocks.full_attention.FullAttention
    num_heads: 4
  time_mixing:
    num_heads: 4